### ISSUE TITLE
Unfinished Business?

### ISSUE THREAD

**Issue by Abab-bk** [Zennyth/EnhancedStat#12]
I tried to use add_stat_modifier(), but it didn't work, so I found the source code:
stat.gd:
```
###
# STAT MODIFIERS
###
func add_stat_modifier(stat_modifier) -> void:
	pass

func remove_stat_modifier(stat_modifier) -> void:
	pass

func clear_stat_modifiers() -> void:
	pass
```
Is this unfinished?

**Comment by Zennyth** [comment]
No it is perfectly normal because stat.gd is an interface, it is up to its inheritors to define its behavior like _computed_stat.gd for example. 

In any case you shouldn’t be using stat, you should use a higher inheritor like FloatStat if you want a stat that represents a float.  

Let me know if you didn’t find what you wanted.

**Comment by Abab-bk** [comment]
I don't know what I did wrong, I just tried to add a modifier, but it does not work:
![image](https://github.com/Zennyth/EnhancedStat/assets/55276676/6ed4304f-2448-4d11-9d2b-fc35c28fdd9e)
![image](https://github.com/Zennyth/EnhancedStat/assets/55276676/2a1788c3-a10a-4a9c-8f1c-a892c9e81858)
![image](https://github.com/Zennyth/EnhancedStat/assets/55276676/6f494cda-df0b-4e62-b070-c00fb43baa94)

**Comment by Abab-bk** [comment]
![image](https://github.com/Zennyth/EnhancedStat/assets/55276676/3be43ca9-3d5b-4938-a884-4d50316250d5)
Due to the return value of get_operation_value() being 0, add_stat_modifier is unable to calculate correctly. This aspect is missing from the documentation and should be added.

**Comment by Abab-bk** [comment]
I'm sorry, I understand now. The actual reason is that the documentation has incorrect information about FloatStatModifier, which doesn't align with the source code.

**Comment by Zennyth** [comment]
Did you fix the problem ? If so, could you point me the parts in the documentation that need to be reworked ?

**Comment by Zennyth** [comment]
Closed via the PR https://github.com/Zennyth/EnhancedStat/pull/13.
