### ISSUE TITLE
NO LINKS

### ISSUE THREAD

**Issue by 1xch** [Zennyth/EnhancedStat#6]
You mention multiple time this is part of suite and even require another package, but there is no link to these from this repo.

**Comment by Zennyth** [comment]
You're right, the documentation mention the use of 'Enhanced Common' addon but don't provide a link for it. This has been fixed.
Here's the addon in case you don't want to scroll through the README.md again ; https://github.com/Zennyth/EnhancedCommon.

Thank you for adressing this issue :)
