### ISSUE TITLE
Empty ZIP and Godot AssetLib package

### ISSUE THREAD

**Issue by UberDan1337** [Zennyth/EnhancedStat#9]
Hey crew, looks like you do good work.

I've tried downloading the code zip, as well as the package through the AssetLib, and they've both been empty files. 

This seems like a very helpful project, I would love to be able to make use of it. 
(I'm new to git, I'm not sure how cordial I should be in these reports)

**Comment by Abab-bk** [comment]
me too.

**Comment by Techypopcorn** [comment]
Yeah I am having the same problem too

**Comment by ArchSinccubus** [comment]
I cloned the git project directly and copied the files. Seems like I can't turn on the plugin due to a lot of errors in the code, namely missing extends, out of scope declares, etc. I would love to use this project too... If there's a fix, I'd love to know about it

**Comment by Sironix** [comment]
Following those tips I was able to use this addon with the enhanced commons addon too (it's required)
but still lots of errors, was able to fix some of them but one of the big ones that I don't know how to solve is also one of the most important parts of the addon.
I hope the addon does keep getting updated, it looks like quite the neat toolto make games with.

**Comment by Zennyth** [comment]
Hey everyone, thank for the issues raised. Sorry for my lack of support regarding this addon, I've taken some time off from gamedev.  From what I can understand, there are two problems : 
- Empty zip
- The plugin is not working anymore due to a conflict with EnhancedCommon

I've just fix the issue with EnhancedCommon by pushing my latest changes to the main from the develop branch.
I'm currently investigating the first one but I'm not that good with git so I'll let you know.

Thank you for taking the time to use this addon :)

**Comment by Sironix** [comment]
Hello Good morning.
Ill test the addon once more once i get back from work.
I dont know too much about github neither but what i did to be able to download the addon was to wdit the git ignore file, looks like with that you can decide what it gets added to the release/download file.
In it, it says that it should ignore the addon folder.
I did a copy of the project, deleted that ñone of clde and was able to download the addon fine.
Anyway, thanks for checking out the issue, i hope you have a really good end of the year!

**Comment by Zennyth** [comment]
Alright, I've modified some git related files to include all files into the zip and modified the godot asset librairy download url.
The changes my take some time to apply but the issue should be resolved.

Let me know if you still have issues with the .zip. See you :)
